// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"pegawaiServices/app"
	"pegawaiServices/controller"
	"pegawaiServices/repository"
	"pegawaiServices/service"
)

// Injectors from injector.go:

func InitializedServer() *echo.Echo {
	pegawaiRepositoryImpl := repository.NewPegawaiRepositoryImpl()
	db := app.GetConnection()
	v := _wireValue
	validate := validator.New(v...)
	pegawaiServiceImpl := service.NewPegawaiServiceImpl(pegawaiRepositoryImpl, db, validate)
	pegawaiControllerImpl := controller.NewPegawaiControllerImpl(pegawaiServiceImpl)
	echoEcho := app.NewRouter(pegawaiControllerImpl)
	return echoEcho
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var pegawaiSet = wire.NewSet(repository.NewPegawaiRepositoryImpl, wire.Bind(new(repository.PegawaiRepository), new(*repository.PegawaiRepositoryImpl)), service.NewPegawaiServiceImpl, wire.Bind(new(service.PegawaiService), new(*service.PegawaiServiceImpl)), controller.NewPegawaiControllerImpl, wire.Bind(new(controller.PegawaiController), new(*controller.PegawaiControllerImpl)))
