CREATE TABLE tb_pegawai (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nama TEXT NOT NULL,
    nip VARCHAR(255) NOT NULL UNIQUE,
    kode_opd VARCHAR(255) NOT NULL,
    status_pegawai VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;