CREATE TABLE tb_pegawai (
    id VARCHAR(255) ,
    nama TEXT NOT NULL,
    nip VARCHAR(255) NOT NULL,
    kode_opd VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;