// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pegawai/create": {
            "post": {
                "description": "Create a new pegawai",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CREATE Pegawai"
                ],
                "summary": "Create Pegawai",
                "parameters": [
                    {
                        "description": "Create Pegawai",
                        "name": "pegawai",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PegawaiCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/pegawai/delete/{id}": {
            "delete": {
                "description": "Delete an existing pegawai",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DELETE Pegawai"
                ],
                "summary": "Delete Pegawai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pegawai ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/pegawai/detail/{id}": {
            "get": {
                "description": "FindById an existing pegawai",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET Pegawai"
                ],
                "summary": "FindById pegawai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pegawai ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/pegawai/findall": {
            "get": {
                "description": "FindAll an existing pegawai",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET Pegawai"
                ],
                "summary": "FindAll pegawai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode OPD",
                        "name": "kode_opd",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/pegawai/findbynip/{nip}": {
            "get": {
                "description": "FindByNip an existing pegawai",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET Pegawai"
                ],
                "summary": "FindByNip pegawai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee NIP",
                        "name": "nip",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/pegawai/update/{id}": {
            "put": {
                "description": "Update an existing pegawai",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UPDATE Pegawai"
                ],
                "summary": "Update Pegawai",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pegawai ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Pegawai",
                        "name": "pegawai",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PegawaiUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.PegawaiCreateRequest": {
            "description": "Create Request Pegawai",
            "type": "object",
            "required": [
                "kode_opd",
                "nama_pegawai",
                "nip"
            ],
            "properties": {
                "kode_opd": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "status_pegawai": {
                    "type": "string",
                    "enum": [
                        "valid",
                        "not_valid"
                    ]
                }
            }
        },
        "web.PegawaiUpdateRequest": {
            "description": "Update Request Pegawai",
            "type": "object",
            "required": [
                "kode_opd",
                "nama_pegawai",
                "nip"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "status_pegawai": {
                    "type": "string",
                    "enum": [
                        "valid",
                        "tidak_valid",
                        "aktif",
                        "non_aktif",
                        "pensiun"
                    ]
                }
            }
        },
        "web.WebResponse": {
            "description": "Web Response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Pegawai Service API",
	Description:      "API For Master Pegawai Services",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
